#This is the compose file that shows the applications working in full effect.
#Does not use docker swarm and just uses docker-compose
version: "3.8"


services:
  db: # Defines the 'db' service for MySQL database
    image: mysql:8.0 
    environment: 
      - MYSQL_DATABASE=fixit_db 
      - MYSQL_PASSWORD=password 
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - sameNetworkAsMysql
    ports:
      - 3307:3306
    volumes:
      - ./database:/docker-entrypoint-initdb.d    
  
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - sameNetworkAsMysql    
  
  solutions: 
    build:
      context: ./solutions 
      dockerfile: dockerfile
    ports:
      - 3000:3000 
    networks:
      - sameNetworkAsMysql
    depends_on:
      - db 
  
  login:
    depends_on:
      - db
    ports:
      - 3003:3003    
    build: 
      context: ./login
      args: 
        ENCRYPT_HOST_IP: 34.129.141.86
    networks:
      - sameNetworkAsMysql
  
  encryption:
    depends_on:
      - login
    ports:
      - 3002:3002    
    build: ./encryption
    networks:
      - sameNetworkAsMysql

  frontend: 
    restart: on-failure 
    build: 
      context: ./frontend
      args:
        REACT_APP_LOGIN_HOST_IP: 34.129.141.86
        REACT_APP_SOLUTIONS_HOST_IP: 34.129.141.86
    ports:
      - 80:3000 
    networks:
      - sameNetworkAsMysql 
    depends_on:
      - solutions

networks:
  sameNetworkAsMysql:
    driver: bridge 
