version: "3.8"

services:
  db: # Defines the 'db' service for MySQL database
    image: mysql:8.0 
    environment: 
      - MYSQL_DATABASE=fixit_db 
      - MYSQL_PASSWORD=password 
      - MYSQL_ROOT_PASSWORD=password
        # networks:
        # - sameNetworkAsMysql
    ports:
      - 3307:3306
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    deploy:
      replicas: 1    
  
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
        #networks:
        #- sameNetworkAsMysql    
  
  solutions:
    image: 127.0.0.1:5000/fixit-solutions 
    build:
      context: ./solutions 
      dockerfile: dockerfile
    ports:
      - 3000:3000 
        #networks:
        #- sameNetworkAsMysql
    depends_on:
      - db
    deploy:
      replicas: 2    
  
  login:
    depends_on:
      - db
    ports:
      - 3003:3003
    image: 127.0.0.1:5000/fixit-login    
    build: 
      context: ./login
      args: 
        ENCRYPT_HOST_IP: 34.129.141.86
          #networks:
          #- sameNetworkAsMysql
    deploy:
      replicas: 2
 
  encryption:
    depends_on:
      - login
    ports:
      - 3002:3002
    image: 127.0.0.1:5000/fixit-encryption    
    build: ./encryption
      #networks:
      #- sameNetworkAsMysql

  frontend: 
    restart: on-failure 
    image: 127.0.0.1:5000/fixit-frontend:latest 
    build: 
      context: ./frontend
      args:
        REACT_APP_SOLUTIONS_HOST_IP: 34.129.141.86
        REACT_APP_LOGIN_HOST_IP: 34.129.141.86  
    ports:
      - 80:3000 
        #networks:
        #- sameNetworkAsMysql 
    depends_on:
      - solutions
    deploy:
      replicas: 3
        #networks:
        #sameNetworkAsMysql:
        #driver: bridge 
